version: '3.3'
services:
  user-db:
    image: mysql:5.7
    container_name: user-db
    restart: always
    environment:
      MYSQL_DATABASE: 'user-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - user-db:/var/lib/mysql
volumes:
  user-db: