version: '3.3'
services:
  order-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: order-db
    restart: always
    environment:
      MYSQL_DATABASE: 'order-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - order-db:/var/lib/mysql

  order-service:
    image: order-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=docker
    restart: always
    depends_on:
      - order-db
    deploy:
      replicas: 2

volumes:
  order-db:

networks:
  default:
    external:
      name: java-graphql-common-network