spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

graphql:
  client:
    url: http://localhost:8080/order-service/graphql
  playground:
    tabs:
      - name: User
        query: classpath:graphql/playground/user.graphql

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/


