spring:
  datasource:
    url: jdbc:mysql://user-db:3306/user-db
  jpa:
    show-sql: true

graphql:
  client:
    url: http://api-gateway:8080/order-service/graphql

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:9000/eureka/