server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3307/order-db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

graphql:
  playground:
    tabs:
      - name: User
        query: classpath:graphql/playground/order.graphql

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/