version: '3.3'
services:
  order-db:
    image: mysql:5.7
    container_name: order-db
    restart: always
    environment:
      MYSQL_DATABASE: 'order-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - order-db:/var/lib/mysql
volumes:
  order-db: