version: '3.8'
services:
  user-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: user-db
    restart: always
    environment:
      MYSQL_DATABASE: 'user-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - user-db:/var/lib/mysql

  user-service:
    image: user-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=docker
    restart: always
    depends_on:
      - user-db
    deploy:
      replicas: 2

volumes:
  user-db:

networks:
  default:
    external:
      name: java-graphql-common-network